parameters:
#    open_ecoles_annexe.example.class: OpenEcoles\AnnexeBundle\Example

services:
#    open_ecoles_annexe.example:
#        class: %open_ecoles_annexe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
