open_ecoles_user:
    resource: "@OpenEcolesUserBundle/Resources/config/routing.yml"
    prefix:   /

open_ecoles_annexe:
    resource: "@OpenEcolesAnnexeBundle/Resources/config/routing.yml"
    prefix:   /annexeDesBundles

open_ecoles_front_office:
    resource: "@OpenEcolesFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /Site

open_ecoles_back_office:
    resource: "@OpenEcolesBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /Admin

open_ecoles_tutorial:
    resource: "@OpenEcolesTutorialBundle/Resources/config/routing.yml"
    prefix:   /Tutoriel