parameters:
#    open_ecoles_open_annonce.example.class: OpenEcoles\OpenAnnonceBundle\Example

services:
#    open_ecoles_open_annonce.example:
#        class: %open_ecoles_open_annonce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
