parameters:
#    open_ecoles_open_seance.example.class: OpenEcoles\OpenSeanceBundle\Example

services:
#    open_ecoles_open_seance.example:
#        class: %open_ecoles_open_seance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    open_ecoles_open_seance_actionBD:
        class: OpenEcoles\TutorialBundle\Services\ActionBDOpenSeance
        arguments: [@doctrine.orm.entity_manager]
