parameters:
#    open_ecoles_open_seance.example.class: OpenEcoles\OpenSeanceBundle\Example

services:
#    open_ecoles_open_seance.example:
#        class: %open_ecoles_open_seance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    open_ecoles_open_seance.gestionOpenSeance:
        class: OpenEcoles\OpenSeanceBundle\Services\ActionBDOpenSeance
        arguments: [@doctrine.orm.entity_manager]

    open_ecoles_open_seance.participationOpenSeance:
        class: OpenEcoles\OpenSeanceBundle\Services\ActionBDParticipantOpenSeance
        arguments: [@doctrine.orm.entity_manager]
