##############################
# Fichier de configuration du bundle Tutoriel
##############################

################################
# Gestion des tutoriel(entity) #
################################

# page du front
open_ecoles_tutorial_homepage:
    pattern:  /
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:accueil }

#page du back
open_ecoles_tutorial_back_homepage:
    pattern:  /Admin
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:backAccueil }

open_ecoles_tutorial_visualiser:
    pattern:  /voir/tutoriel/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:visualiserTutoriel }

open_ecoles_tutorial_visualiser_tutoriels:
    pattern:  /voir/tutoriels
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:visualiserTutorielBack }

open_ecoles_tutorial_ajout:
    pattern:  /ajouter
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:creerTutoriel }

open_ecoles_tutorial_modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:modifierTutoriel }

open_ecoles_tutorial_supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:supprimerTutoriel }

open_ecoles_tutorial_valider:
    pattern:  /valider/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:validerTutoriel }


###############################
#    Gestion des chapitres    #
###############################
open_ecoles_tutorial_homepage_chapitre:
    pattern:  /
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:accueil }

open_ecoles_tutorial_visualiser_section:
    pattern:  /section/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:visualiserChapitre }

open_ecoles_tutorial_ajout_section:
    pattern:  /ajouter/section/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:creerSection }

open_ecoles_tutorial_modifier_section:
    pattern:  /modifier/section/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:modifierChapitre }

open_ecoles_tutorial_supprimer_section:
    pattern:  /supprimer/section/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:supprimerSection }

open_ecoles_tutorial_visualiser_chapitre:
    pattern:  /chapitre/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:visualiserChapitre }

open_ecoles_tutorial_ajout_chapitre:
    pattern:  /ajouter/chapitre/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:creerChapitre }

open_ecoles_tutorial_modifier_chapitre:
    pattern:  /modifier/chapitre/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:modifierChapitre }

open_ecoles_tutorial_supprimer_chapitre:
    pattern:  /supprimer/chapitre/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Chapitre:supprimerChapitre }

open_ecoles_tutorial_mes_documents:
    pattern: /mesDocuments
    defaults: {_controller: OpenEcolesTutorialBundle:Tutoriel:mesDocuments }

open_ecoles_tutorial_afficher_plus:
    pattern: /tutoriels/categorie/{id}
    defaults: { _controller: OpenEcolesTutorialBundle:Tutoriel:visualiserAllTutorielByCategory}
#####################################
#   Gestion des catégories de tuto  #
#####################################

open_ecoles_tutorial_categorie:
    pattern: /categorie
    defaults: {_controller:OpenEcolesTutorialBundle:Category:index}

#####################################
# Gestion des notes                 #
#####################################
open_ecoles_tutorial_noter_tutoriel:
    pattern: /noter/{id}
    defaults: {_controller:OpenEcolesTutorialBundle:Note:noterTutoriel}
    requirements:
        _method: POST