services:

    open_ecoles_tutorial.gestionChapitre:
        class: OpenEcoles\TutorialBundle\Services\ActionBDChapitre
        arguments: [@doctrine.orm.entity_manager]

    open_ecoles_tutorial.gestiontutoriel:
        class: OpenEcoles\TutorialBundle\Services\ActionBDTutoriel
        arguments: [@doctrine.orm.entity_manager,@open_ecoles_tutorial.gestionChapitre]

    open_ecoles_tutorial.gestionCategorie:
        class: OpenEcoles\TutorialBundle\Services\ActionBDCategorie
        arguments: [@doctrine.orm.entity_manager]

    open_ecoles_tutorial.gestionNote:
        class: OpenEcoles\TutorialBundle\Services\ActionBDNote
        arguments: [@doctrine.orm.entity_manager]


    open_ecoles_tutorial.validationTutoriel:
        class: OpenEcoles\TutorialBundle\Services\validateTutoriel
        public: true

#    open_ecoles_tutorial.example:
#        class: %open_ecoles_tutorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]