services:
    open_ecoles_tutorial.gestiontutoriel:
        class: OpenEcoles\TutorialBundle\Services\ActionBDTutoriel
        arguments: [@doctrine.orm.entity_manager]

    open_ecoles_tutorial.validationTutoriel:
        class: OpenEcoles\TutorialBundle\Services\validateTutoriel
        public: true
        scope: request


#    open_ecoles_tutorial.example:
#        class: %open_ecoles_tutorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]