<?php

namespace OpenEcoles\OpenSeanceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantOpenSeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantOpenSeanceRepository extends EntityRepository
{
}
