<?php

namespace OpenEcoles\TutorialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UniteTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteTexteRepository extends EntityRepository
{
}
