<?php

namespace Proxies\__CG__\OpenEcoles\TutorialBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Chapitre extends \OpenEcoles\TutorialBundle\Entity\Chapitre implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setParent(\OpenEcoles\TutorialBundle\Entity\Chapitre $parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setTutoriel(\OpenEcoles\TutorialBundle\Entity\Tutoriel $tutoriel = NULL)
    {
        $this->__load();
        return parent::setTutoriel($tutoriel);
    }

    public function getTutoriel()
    {
        $this->__load();
        return parent::getTutoriel();
    }

    public function setOrdre($ordre)
    {
        $this->__load();
        return parent::setOrdre($ordre);
    }

    public function getOrdre()
    {
        $this->__load();
        return parent::getOrdre();
    }

    public function setOrderParent($orderParent)
    {
        $this->__load();
        return parent::setOrderParent($orderParent);
    }

    public function getOrderParent()
    {
        $this->__load();
        return parent::getOrderParent();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'ordre', 'parent', 'tutoriel');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}