<?php
/**
 * Created by PhpStorm.
 * User: barry
 * Date: 09/01/14
 * Time: 20:25
 */

namespace OpenEcoles\UserBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class MessageRepository extends EntityRepository {

} 