parameters:
#    open_ecoles_user.example.class: OpenEcoles\UserBundle\Example

services:
#    open_ecoles_user.example:
#        class: %open_ecoles_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
